-- Date Exploration --

-- 1- Find the date of the first and last order
select 
MIN(order_date) as first_order_date,
Max(order_date) as Last_Order_date
from gold.fact_sales

-- 2- How many years of sales are avaiable
select 
MIN(order_date) as first_order_date,
Max(order_date) as Last_Order_date,
DateDiff(YEAR,MIN(order_date),Max(order_date)) as Order_range_years
from gold.fact_sales

-- 3- Find the youngest and the oldest customer
Select 
Min(birthdate) as The_youngest_Customer,
DATEDIFF(year,Min(birthdate),GETDATE()) as Oldest_Age,
Max(birthdate) as The_Oldest_Customer,
DATEDIFF(year,Max(birthdate),GETDATE()) as Youngest_Age
from gold.dim_customers

-- Measures Exploration --

-- 1- Find the Total Sales

select  sum(sales_amount) as Total_Sales
from gold.fact_sales

-- 2-Find how many items are sold

select sum(quantity) as Total_Items_sold
from gold.fact_sales

-- 3-Find the average selling price

select AVG(price) as Average_Selling_Price
from gold.fact_sales

-- 4-Find the Total number of Orders
Select COUNT(order_number) as Total_Orders
from gold.fact_sales
-- 5- Unique orders number
Select COUNT(distinct order_number) as Total_Orders
from gold.fact_sales

-- 6- find the total number of products

Select COUNT(product_id) as Total_Products
from gold.dim_products
Select COUNT(distinct product_id) as Total_Products
from gold.dim_products

-- 7- Find the total number of customers

Select COUNT(customer_id) as Total_customers
from gold.dim_customers

-- 8- Find the total number of customers that has placed an order
select count(distinct customer_Key) as Customers_With_Orders
from gold.fact_sales

-- 9- Generate a Report that shows all key metrics of the business
select 'Total Sales' as Mesure_name, SUM(sales_amount) As Measure_value From gold.fact_sales
union All
select 'Total Quantity', SUM(quantity)  From gold.fact_sales
union All
select 'Average Price', Avg(Price)  From gold.fact_sales
union All
select 'Total Nr. Orders', Count(Distinct order_number) From gold.fact_sales
union All
select 'Total Nr. Products', Count(product_name) From gold.dim_products
union all
select 'Total Nr. Customers', Count(customer_key) From gold.dim_customers

-- Magnitude -- 

-- 1-Find total customers by countries

select country, count(customer_id) as Total_Customers
from gold.dim_customers
Group by country 
order by Total_Customers Desc

-- 2-Find total customers by gender

select gender, count(customer_id) as Total_Customers
from gold.dim_customers
Group by gender 
order by Total_Customers Desc

-- 3-Find total products by category

select category , count(product_id) as Total_Products
from gold.dim_products
Group by category 
order by Total_Products Desc

-- 4-What is the average costs in each category?

select category, AVG(cost) as Average_Cost
from gold.dim_products
Group by category
order by Average_Cost desc

-- 5-What is the total revenue generated for each category?

select category, SUM(quantity*price) as Total_Revenue
from 
gold.fact_sales S
left join
gold.dim_products P
on s.product_key=p.product_key
Group by category
order by Total_Revenue desc

-- 6-Find total revenue is generated by each customer

select c.customer_key, c.first_name, c.last_name , SUM(quantity*price) as Total_Revenue
from 
gold.fact_sales S
left join
gold.dim_customers C
on s.customer_key=c.customer_key
Group by c.customer_key,first_name, last_name

order by Total_Revenue desc

-- 7-What is the distribution of sold items across countries?

select c.country , SUM(quantity) as Total_Sold_Items
from 
gold.fact_sales S
left join
gold.dim_customers C
on s.customer_key=C.customer_key
Group by c.country
order by Total_Sold_Items desc


-- RANKING -- 

-- 1- Which 5 products generate the highest revenue?
select top 5 product_id, product_name, sum(price*Quantity) as Total_Revenue
from gold.fact_sales S
left join 
gold.dim_products  P
on s.product_key=p.product_key
Group by product_id, product_name
order by Total_Revenue desc

-- 2- What are the 5 worst-performing products in terms of sales?

select top 5 product_id, product_name, sum(price*Quantity) as Total_Revenue
from gold.fact_sales S
left join 
gold.dim_products  P
on s.product_key=p.product_key
Group by product_id, product_name
order by Total_Revenue asc
